---
################################################################################
# Application
################################################################################
application:
- '.github/actions/setup-aqua/action.yaml'
- '.github/workflows/application.yml'
- '.aqua.yaml'
- '.octocov.yml'
- 'Taskfile.yml'
- 'tasks/**.task.yml'
- 'go.mod'
- 'go.sum'
- '**.go'
################################################################################
# Renovate Config Validator
################################################################################
renovate-config-validator:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-bun/action.yaml'
- '.github/workflows/renovate-config-validator.yml'
- '.renovaterc.json'
- 'bun.lockb'
- 'package.json'
################################################################################
# Reviewdog (actionlint)
################################################################################
reviewdog-actionlint:
- '.github/actions/*.yml'
- '.github/actions/*.yaml'
- '.github/workflows/*.yml'
- '.github/workflows/*.yaml'
- '.aqua.yaml'
- '.reviewdog.yml'
################################################################################
# Reviewdog (editorconfig-checker)
################################################################################
reviewdog-editorconfig-checker:
- '**'
- '!LICENSE'
- '!bun.lockb'
- '!**.md'
################################################################################
# Reviewdog (gjson-validate)
################################################################################
reviewdog-gjson-validate:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-gjson-validate.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- '**.json'
- '**.json.golden'
- '!**.invalid.json.golden'
################################################################################
# Reviewdog (gofmt)
################################################################################
reviewdog-gofmt:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-gofmt.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- '**.go'
################################################################################
# Reviewdog (gosec)
################################################################################
reviewdog-gosec:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-gosec.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- 'go.mod'
- 'go.sum'
- '**.go'
################################################################################
# Reviewdog (govet)
################################################################################
reviewdog-govet:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-govet.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- 'go.mod'
- 'go.sum'
- '**.go'
################################################################################
# Reviewdog (gyaml-validate)
################################################################################
reviewdog-gyaml-validate:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-gyaml-validate.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- '**.yml'
- '**.yaml'
################################################################################
# Reviewdog (shellcheck)
################################################################################
reviewdog-shellcheck:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-shellcheck.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- '**.sh'
- '**.bash'
################################################################################
# Reviewdog (shfmt)
################################################################################
reviewdog-shfmt:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-shfmt.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- '**.sh'
- '**.bash'
################################################################################
# Reviewdog (staticcheck)
################################################################################
reviewdog-staticcheck:
- '.github/actions/setup-aqua/action.yaml'
- '.github/actions/setup-reviewdog/action.yaml'
- '.github/workflows/reviewdog-staticcheck.yml'
- '.aqua.yaml'
- '.reviewdog.yml'
- 'go.mod'
- 'go.sum'
- '**.go'
