---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v3.55.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2022.1
- name: goreleaser/goreleaser@v1.11.3
- name: securego/gosec@v2.13.1
