coverage:
  if: true
  paths:
  - coverage.out
codeToTestRatio:
  if: true
  code:
  - '**/*.go'
  - '!**/*_test.go'
  test:
  - '**/*_test.go'
testExecutionTime:
  if: true
summary:
  if: true
comment:
  if: is_pull_request
diff:
  if: is_pull_request
  datastores:
  - artifact://${GITHUB_REPOSITORY}
report:
  if: is_pull_request
  datastores:
  - artifact://${GITHUB_REPOSITORY}
