coverage:
  paths:
  - coverage.out
codeToTestRatio:
  code:
  - '**/*.go'
  - '!**/*_test.go'
  test:
  - '**/*_test.go'
testExecutionTime:
summary:
  hideFooterLink: true
body:
  hideFooterLink: true
comment:
  if: is_pull_request
  hideFooterLink: true
diff:
  datastores:
  - artifact://${GITHUB_REPOSITORY}
report:
  datastores:
  - artifact://${GITHUB_REPOSITORY}
