repository: takumin/boilerplate-golang-cli
push:
coverage:
  badge:
    path: docs/coverage.svg
  paths:
  - coverage.out
codeToTestRatio:
  badge:
    path: docs/ratio.svg
  code:
  - '**/*.go'
  - '!**/*_test.go'
  test:
  - '**/*_test.go'
testExecutionTime:
  badge:
    path: docs/time.svg
