---
# https://taskfile.dev

version: '3'

includes:
  tool: ./tasks/tool.task.yml
  reviewdog: ./tasks/reviewdog.task.yml
  go: ./tasks/go.task.yml

tasks:
  default:
    silent: true
    deps:
    - task: tool
    - task: reviewdog
    - task: go
  test:
    silent: true
    deps:
    - task: go:{{.TASK}}
  build:
    silent: true
    deps:
    - task: go:{{.TASK}}
  clean:
    silent: true
    deps:
    - task: go:{{.TASK}}
