---
# https://taskfile.dev

version: '3'

includes:
  tool: ./tasks/tool.task.yml
  format: ./tasks/format.task.yml
  reviewdog: ./tasks/reviewdog.task.yml
  go: ./tasks/go.task.yml

tasks:
  default:
    silent: true
    deps: [aqua]
    cmds:
    - task: tool
    - task: format
    - task: reviewdog
    - task: go
  aqua:
    run: once
    sources:
    - .aqua.yaml
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - aqua install --all
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
  test:
    silent: true
    deps:
    - task: go:{{.TASK}}
  build:
    silent: true
    deps:
    - task: go:{{.TASK}}
  clean:
    silent: true
    deps:
    - task: go:{{.TASK}}
