---
# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    deps:
    - pinact
    - ghalint

  pinact:
    run: once
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - pinact run
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  ghalint:
    run: once
    deps: [pinact]
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - ghalint run
    - ghalint act
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
