---
name: Setup Aqua
description: Setup Aqua by using cache and environment variables
inputs:
  go-cache:
    description: golang actions cache enabled
    required: false
    default: 'false'
runs:
  using: composite
  steps:
  - name: Get Go Version
    id: go
    shell: bash
    run: echo "version=$(grep -E '^go' ${{ github.workspace }}/go.mod | sed -E 's/ //')" >> $GITHUB_OUTPUT
  - name: Allow Local Registry
    shell: bash
    run: echo "AQUA_POLICY_CONFIG=${{ github.workspace }}/.aqua-policy.yaml" >> $GITHUB_ENV
  - name: Aqua Tools Cache
    uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      path: ~/.local/share/aquaproj-aqua
      key: aqua-${{ runner.os }}-${{ steps.go.version }}-${{ hashFiles('**/.aqua.yaml') }}
  - name: Golang Build Cache
    uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      path: ~/.cache/go-build
      key: go-build-${{ runner.os }}-${{ steps.go.version }}-${{ hashFiles('**/go.sum') }}
      lookup-only: ${{ inputs.go-cache == 'false' }}
  - name: Golang Mod Cache
    uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      path: ~/go/pkg/mod
      key: go-build-${{ runner.os }}-${{ steps.go.version }}-${{ hashFiles('**/go.sum') }}
      lookup-only: ${{ inputs.go-cache == 'false' }}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
    with:
      aqua_version: v2.38.3
      enable_aqua_install: false
  - name: Install Tools
    shell: bash
    run: |-
      aqua install --exclude-tags go --all
      aqua install --all
