---
name: Setup Aqua
description: Setup Aqua by using cache and environment variables
runs:
  using: composite
  steps:
  - name: Set Go Cache Path
    shell: bash
    run: |
      echo GOPATH="${HOME}/.local/share/aquaproj-aqua-go" >> "$GITHUB_ENV"
      echo GOCACHE="${HOME}/.local/share/aquaproj-aqua-go/bld" >> "$GITHUB_ENV"
  - name: Allow Local Registry
    shell: bash
    run: echo "AQUA_POLICY_CONFIG=${{ github.workspace }}/.aqua-policy.yaml" >> "$GITHUB_ENV"
  - name: Restore Aqua Cache
    uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      key: aqua-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/.aqua.yaml') }}
      path: |
        ~/.local/share/aquaproj-aqua
        ~/.local/share/aquaproj-aqua-go
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
    with:
      aqua_version: v2.38.4
      enable_aqua_install: false
  - name: Install Tools
    shell: bash
    run: |-
      aqua install --exclude-tags go --all
      aqua install --all
  - name: Get Default Branch
    id: gh
    env:
      GH_TOKEN: ${{ github.token }}
    shell: bash
    run: echo default_branch_ref_name="$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)" >> "$GITHUB_OUTPUT"
  - name: Show Branch
    shell: bash
    run: |
      echo '"${{ github.ref_name }}"'
      echo '"${{ steps.gh.outputs.default_branch_ref_name }}"'
  - name: Save Aqua Cache
    if: github.ref_name == steps.gh.outputs.default_branch_ref_name
    uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      key: aqua-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/.aqua.yaml') }}
      path: |-
        ~/.local/share/aquaproj-aqua
        ~/.local/share/aquaproj-aqua-go
