name: Cleanup Actions Cache
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    name: Run Actions Cache
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: GitHub Actions Cache Version
      run: |
        date +%s > .github/actions-cache-version
    - name: Commit & Push
      uses: actions-js/push@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'ci: clear github actions cache'
