---
name: Renovate Config Validator
on:
  workflow_call:
permissions: {}
concurrency:
  group: renovate-config-validator-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Aqua
      uses: ./.github/actions/setup-aqua
    - name: Setup Bun
      uses: ./.github/actions/setup-bun
    - name: Renovate Config Validator
      run: bun run renovate-config-validator --strict
